[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/docker-entrypoint.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Tell Railway which port your app listens on
healthcheckPath = "/"
healthcheckTimeout = 100